# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 3.0.0
maven_group = com.github.peterservices
archives_name = autohidehotbar
enabled_platforms = fabric,neoforge
display_name = Auto-Hide Hotbar
description = Automatic HUD dimming and hiding when not in use.
author = Ticataco
credits = AlphaYT (Original Creator)
license = MIT

# Minecraft properties
minecraft_version = 26.1.2

# Fabric Properties
fabric_loader_minimum = 0.18.4
minecraft_minimum = 26.1
architectury_minimum = 20

# NeoForge properties
minecraft_range = [26.1,26.2)
loader_range = [10,)
neoforge_range = [26.1,)
architectury_range = [20,)

# Dependencies
architectury_api_version = 20.0.9
fabric_loader_version = 0.19.3
fabric_api_version = 0.155.2+26.1.2
neoforge_version = 26.1.2.86
midnightlib_version = 1.9.3+26.1