# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 2.2.0
maven_group = com.github.peterservices
archives_name = autohidehotbar
enabled_platforms = fabric,neoforge
display_name = Auto-Hide Hotbar
description = Automatic HUD hiding when not in use.
author = Ticataco
credits = AlphaYT (Original Creator)
license = MIT

# Minecraft properties
minecraft_version = 26.2

# Fabric Properties
fabric_loader_minimum = 0.18.4
minecraft_minimum = 26.2

# NeoForge properties
minecraft_range = [26.2,26.3)
loader_range = [10,)
neoforge_range = [26.2,)
architectury_range = [21,)

# Dependencies
architectury_api_version = 21.0.2
fabric_loader_version = 0.19.3
fabric_api_version = 0.152.1+26.2
neoforge_version = 26.2.0.1-beta
midnightlib_version = 1.9.3+26.2