modLoader = "javafml"
loaderVersion = "${loader_range}"
issueTrackerURL = "${issue_tracker}"
license = "${license}"

[[mods]]
modId = "autohidehotbar"
version = "${version}"
displayName = "${display_name}"
authors = "${author}, ${credits}"
description = "${description}"
modUrl = "${source}"
logoFile = "assets/autohidehotbar/icon.png"

[[dependencies.autohidehotbar]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.autohidehotbar]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.autohidehotbar]]
modId = "architectury"
type = "required"
versionRange = "${architectury_range}"
ordering = "AFTER"
side = "CLIENT"

[mc-publish]
dependencies=[
    "midnightlib@${midnightlib_version}(embedded){modrinth:codAaoxh}{curseforge:488090}",
    "architectury(required){modrinth:lhGA9TYQ}{curseforge:419699}"
]

[[mixins]]
config = "autohidehotbar.mixins.json"
