name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download release
        uses: robinraju/release-downloader@v1
        with:
          tag: ${{ github.ref_name }}
          fileName: '*.jar'
        
      - name: Publish Fabric mod to Modrinth and CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: B49AL3Br
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 1573239
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          loaders: |
            fabric

          files: |
            autohidehotbar-fabric-*.jar

      - name: Publish NeoForge mod to Modrinth and CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: B49AL3Br
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 1573239
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          loaders: |
            neoforge

          files: |
            autohidehotbar-neoforge-*.jar
